client:
  post:
    baseUrl: https://jsonplaceholder.typicode.com

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC

openexchangeratesApi:
  baseUrl: https://openexchangerates.org/api
  appId: 7abfe791460a4e61ba36aaa62b1581d1
  baseCurrency: USD

giphyApi:
  baseUrl: https://api.giphy.com/v1/gifs
  appId: Frs7oIQESxBl3ZR7UeSYOJNYgKx5Wmuc